routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

    Route::get('/Dashboard', function () {
        return view('admin.index');
    })->name('Dashboard');
Route::resource('/Pages', App\Http\Controllers\admin\PageController::class);
Route::get('/search','App\Http\Controllers\admin\PageController@search')->name('search');
Route::get('/Pages_index2','App\Http\Controllers\admin\PageController@indexDatatable')->name('search');
Route::get('datatable_show', [
    'uses' => 'App\Http\Controllers\admin\PageController@productsDataSource'
]);

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify'=>true]);

Route::get('/', function () {
    return view('frontend.index');
})->middleware(['auth','verified'])->name('home');

Route::get('redirect/{service}','SocialController@redirect');
Route::get('callback/{service}','SocialController@callback');
Route::get('send_mail', 'HomeController@send_emails');
Route::post('admin/Pages/store', 'HomeController@send_emails');

resources/views/admin/include/foot.blade.php
<!-- container-scroller -->
<!-- plugins:js -->
<script src={{url('admin/vendors/js/vendor.bundle.base.js')}}></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src={{url('admin/vendors/chart.js/Chart.min.js')}}></script>
<script src={{url('admin/vendors/progressbar.js/progressbar.min.js')}}></script>
<script src={{url('admin/vendors/jvectormap/jquery-jvectormap.min.js')}}></script>
<script src={{url('admin/vendors/jvectormap/jquery-jvectormap-world-mill-en.js')}}></script>
<script src={{url('admin/vendors/owl-carousel-2/owl.carousel.min.js')}}></script>
<!-- End plugin js for this page -->
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<!-- inject:js -->
<script src={{url('admin/js/off-canvas.js")')}}></script>
<script src={{url('admin/js/hoverable-collapse.js')}}></script>
<script src={{url('admin/js/misc.js')}}></script>
<script src={{url('admin/js/settings.js')}}></script>
<script src={{url('admin/js/todolist.js')}}></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<!-- endinject -->
<!-- Custom js for this page -->
<script src={{url('admin/js/dashboard.js')}}></script>
<!-- End custom js for this page -->

resources/views/admin/include/footer.blade.php
    <!-- content-wrapper ends -->

    <!-- partial:partials/_footer.html -->
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span>
        </div>
    </footer>
    <!-- partial -->

resources/views/admin/include/head.blade.php
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Control Panel</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href={{url("admin/vendors/mdi/css/materialdesignicons.min.css")}}>
    <link rel="stylesheet" href={{url("admin/vendors/css/vendor.bundle.base.css")}}>
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href={{url("admin/vendors/jvectormap/jquery-jvectormap.css")}}>
    <link rel="stylesheet" href={{url("admin/vendors/flag-icon-css/css/flag-icon.min.css")}}>
    <link rel="stylesheet" href={{url("admin/vendors/owl-carousel-2/owl.carousel.min.css")}}>
    <link rel="stylesheet" href={{url("admin/vendors/owl-carousel-2/owl.theme.default.min.css")}}>
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    @if(LaravelLocalization::getCurrentLocale()=="ar")
        <link rel="stylesheet" href={{url("admin/css/rtl.css")}}>
    @else
    <link rel="stylesheet" href={{url("admin/css/style.css")}}>
    @endif
    <!-- End layout styles -->
    <link rel="shortcut icon" href={{url("admin/images/favicon.png" )}}/>
</head>

resources/views/admin/include/header.blade.php
<!-- partial -->
{{--<div class="container-fluid page-body-wrapper">--}}
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar p-0 fixed-top d-flex flex-row">
        <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src={{url("admin/images/logo-mini.svg")}} alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-menu"></span>
            </button>
            <ul class="navbar-nav w-100">
                <li class="nav-item w-100">
                    <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                        <input type="text" class="form-control" placeholder="{{__('admin.search_product')}}">
                    </form>
                </li>
            </ul>

            <ul class="navbar-nav navbar-nav-right">

                <li class="nav-item dropdown">
                    <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                        <div class="navbar-profile">
                            <p class="mb-0 d-none d-sm-block navbar-profile-name ">
                                {{ LaravelLocalization::getCurrentLocaleNative() }}

                            </p>
                            <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                        @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                            @if($localeCode==LaravelLocalization::getCurrentLocale())
                                @continue
                            @endif
                        <a class="dropdown-item preview-item justify-content-center"  hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">

                            <div class="preview-item-content">
                                <p class="preview-subject mb-1">{{ $properties['native'] }}
                                </p>
                            </div>
                        </a>

                        @endforeach
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav navbar-nav-right">

                <li class="nav-item dropdown">
                    <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                        <div class="navbar-profile">
                            <img class="img-xs rounded-circle" src={{url( Auth::user()->photo )}} alt="">
                            <p class="mb-0 d-none d-sm-block navbar-profile-name">
                                {{ Auth::user()->name }}
                            </p>
                            <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                        <h6 class="p-3 mb-0">{{ __('admin.profile') }}</h6>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item preview-item">
                            <div class="preview-thumbnail">
                                <div class="preview-icon bg-dark rounded-circle">
                                    <i class="mdi mdi-settings text-success"></i>
                                </div>
                            </div>
                            <div class="preview-item-content">
                                <p class="preview-subject mb-1">{{ __('admin.settings') }}</p>
                            </div>
                        </a>
                        <a href="#" class="dropdown-item preview-item">
                            <div class="preview-thumbnail">
                                <div class="preview-icon bg-dark rounded-circle">
                                    <i class="mdi mdi-onepassword  text-info"></i>
                                </div>
                            </div>
                            <div class="preview-item-content">
                                <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                            </div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item preview-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <div class="preview-thumbnail">
                                <div class="preview-icon bg-dark rounded-circle">
                                    <i class="mdi mdi-logout text-danger"></i>
                                </div>
                            </div>
                            <div class="preview-item-content">
                                <p class="preview-subject mb-1">{{ __('admin.logout') }}
                                </p>
                            </div>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </a>

                    </div>
                </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-format-line-spacing"></span>
            </button>
        </div>
    </nav>
    <!-- partial -->

{{--</div>--}}

resources/views/admin/include/sidebar.blade.php
    <!-- partial:partials/_sidebar.html -->
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <div class="sidebar-brand-wrapper d-none d-lg-flex  fixed-top" style="padding-top: 15px;
    padding-left: 25px;">
           <p class="text-white" style="font-size: 25px;">{{__('admin.project_name')}}</p>
        </div>
        <ul class="nav">
            <li class="nav-item profile">
                <div class="profile-desc">
                    <div class="profile-pic">
                        <div class="count-indicator">
                            <img class="img-xs rounded-circle " src={{url( Auth::user()->photo )}} alt="">
                            <span class="count bg-success"></span>
                        </div>
                        <div class="profile-name">
                            <h5 class="mb-0 font-weight-normal"> {{ Auth::user()->name }}</h5>
                        </div>
                    </div>

                </div>
            </li>
            <li class="nav-item menu-items">
                <a class="nav-link" href="{{route('home')}}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
                    <span class="menu-title">{{__('admin.website')}}</span>
                </a>
            </li>


            <li class="nav-item menu-items">
                <a class="nav-link" href="">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
                    <span class="menu-title">{{__('admin.dashboard')}}</span>
                </a>
            </li>


            <li class="nav-item menu-items">
                <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <span class="menu-icon">
                <i class="mdi mdi-laptop"></i>
              </span>
                    <span class="menu-title">{{__('admin.pages')}}</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="ui-basic">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"> <a class="nav-link" href="{{route('Pages.index')}}">{{__('admin.list')}}</a></li>
                        <li class="nav-item"> <a class="nav-link" href="{{route('Pages.create')}}">{{__('admin.add')}} {{__('admin.page')}}</a></li>
                    </ul>
                </div>
            </li>


        </ul>
    </nav>