routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

    Route::get('/Dashboard', function () {
        return view('admin.index');
    })->name('Dashboard');
Route::resource('/Pages', App\Http\Controllers\admin\PageController::class);
Route::get('/search','App\Http\Controllers\admin\PageController@search')->name('search');
Route::get('/Pages_index2','App\Http\Controllers\admin\PageController@indexDatatable')->name('search');
Route::get('datatable_show', [
    'uses' => 'App\Http\Controllers\admin\PageController@productsDataSource'
]);

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify'=>true]);

Route::get('/', function () {
    return view('frontend.index');
})->middleware(['auth','verified'])->name('home');

Route::get('redirect/{service}','SocialController@redirect');
Route::get('callback/{service}','SocialController@callback');
Route::get('send_mail', 'HomeController@send_emails');
Route::post('admin/Pages/store', 'HomeController@send_emails');

resources/views/admin/pages/create.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> {{__('admin.page')}} </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">{{__('admin.pages')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{__('admin.add')}} {{__('admin.page')}}</li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="card col-md-12">
                <div class="card-body">
                    @if(Session::has('success'))
                    <div class="alert alert-success" role="alert">
                        {{Session::get('success')}}
                    </div>
                    <br>
                    @endif
                    <form class="forms-sample" action="{{route('Pages.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputName1">{{__('admin.name_en')}}</label>
                            <input type="text" class="form-control" id="name_en" name="name_en" placeholder="{{__('admin.name_en')}}">
                        </div>
                        @error('name_en')
                        <span style="color: darkred;" >
                                       * <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                        <div class="form-group">
                            <label for="exampleInputName1">{{__('admin.name_ar')}}</label>
                            <input type="text" class="form-control" id="name_ar" name="name_ar" placeholder="{{__('admin.name_ar')}}">
                        </div>
                        @error('name_ar')

                        <span style="color: darkred;" >
                                       * <strong>{{ $message }}</strong>
                                    </span>
                        <br>

                        @enderror


                        <label for="exampleInputName1">{{__('admin.photo')}}</label>

                        <div class="container">
                            <div class="wrapper">
                                <div class="image">
                                    <img src="" alt="" id="upload_image"/>
                                </div>
                                <div class="content">
                                    <div class="icon">
                                        <i class="fas fa-cloud-upload-alt"></i>
                                    </div>
                                    <div class="text">
                                        {{__('admin.no_file')}}
                                    </div>
                                </div>
                                <div id="cancel-btn">
                                    <i class="fas fa-times"></i>
                                </div>
                                <div class="file-name">
                                    {{__('admin.file_name_here')}}
                                </div>
                            </div>
                            <button type="button" onclick="defaultBtnActive()" id="custom-btn">{{__('admin.choose_file')}}</button>
                            <input id="default-btn" type="file" hidden="hidden" name="photo">
                        </div>
                        @error('photo')

                        <span style="color: darkred;" >
                                       * <strong>{{ $message }}</strong>
                                    </span>
                        <br>

                        @enderror
                        <button type="submit" class="btn btn-primary mr-2">{{__('admin.save')}}</button>
                        <a class="btn btn-dark" href="{{route('Pages.index')}}"> {{__('admin.cancel')}}</a>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <!-- content-wrapper ends -->
@endsection
@section('script')
  <script>

    const wrapper = document.querySelector(".wrapper");
    const fileName = document.querySelector(".file-name");
    const defaultBtn = document.querySelector("#default-btn");
    const customBtn = document.querySelector("#custom-btn");
    const cancelBtn = document.querySelector("#cancel-btn i");
    const img = document.querySelector("#upload_image");
    let regExp = /[0-9a-zA-Z\^\&\'\@\{\}\[\]\,\$\=\!\-\#\(\)\.\%\+\~\_ ]+$/;
    function defaultBtnActive(){
        defaultBtn.click();
    }
    defaultBtn.addEventListener("change", function(){
        const file = this.files[0];
        if(file){
            const reader = new FileReader();
            reader.onload = function(){
                const result = reader.result;
                console.log(result)
                img.src = result;
                wrapper.classList.add("active");
            }
            cancelBtn.addEventListener("click", function(){
                img.src = "";
                wrapper.classList.remove("active");
            })
            reader.readAsDataURL(file);
        }
        if(this.value){
            let valueStore = this.value.match(regExp);
            fileName.textContent = valueStore;
        }
    });
  </script>
    @stop

resources/views/admin/pages/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> {{__('admin.page')}} </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">{{__('admin.pages')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{__('admin.add')}} {{__('admin.page')}}</li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="card col-md-12">
                <div class="card-body">
                    @if(Session::has('success'))
                        <div class="alert alert-success" role="alert">
                            {{Session::get('success')}}
                        </div>
                        <br>
                    @endif
                    <form class="forms-sample" action="{{route('Pages.update',$page['id'])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="exampleInputName1">{{__('admin.name_en')}}</label>
                            <input type="text" class="form-control" id="name_en" name="name_en" placeholder="{{__('admin.name_en')}}" value="{{$page['name_en']}}">
                        </div>
                        @error('name_en')
                        <span style="color: darkred;" >
                                       * <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                        <div class="form-group">
                            <label for="exampleInputName1">{{__('admin.name_ar')}}</label>
                            <input type="text" class="form-control" id="name_ar" name="name_ar" placeholder="{{__('admin.name_ar')}}" value="{{$page['name_ar']}}">
                        </div>
                        @error('name_ar')

                        <span style="color: darkred;" >
                                       * <strong>{{ $message }}</strong>
                                    </span>
                        <br>

                        @enderror
                        <label for="exampleInputName1">{{__('admin.photo')}}</label>

                        <div class="container">
                            <div class="wrapper">
                                <div class="image">
                                    <img src="{{url($page['photo'])}}" alt="" id="upload_image"/>
                                </div>
                                <div class="content">
                                    <div class="icon">
                                        <i class="fas fa-cloud-upload-alt"></i>
                                    </div>
                                    <div class="text">
                                        {{__('admin.no_file')}}
                                    </div>
                                </div>
                                <div id="cancel-btn">
                                    <i class="fas fa-times"></i>
                                </div>
                                <div class="file-name">
                                    {{__('admin.file_name_here')}}
                                </div>
                            </div>
                            <button type="button" onclick="defaultBtnActive()" id="custom-btn">{{__('admin.choose_file')}}</button>
                            <input id="default-btn" type="file" hidden="hidden" name="photo" >
                        </div>
                        @error('photo')

                        <span style="color: darkred;" >
                                       * <strong>{{ $message }}</strong>
                                    </span>
                        <br>

                        @enderror



                        <button type="submit" class="btn btn-primary mr-2">{{__('admin.save')}}</button>
                        <a class="btn btn-dark" href="{{route('Pages.index')}}"> {{__('admin.cancel')}}</a>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <!-- content-wrapper ends -->
@endsection
@section('script')
    <script>

        const wrapper = document.querySelector(".wrapper");
        const fileName = document.querySelector(".file-name");
        const defaultBtn = document.querySelector("#default-btn");
        const customBtn = document.querySelector("#custom-btn");
        const cancelBtn = document.querySelector("#cancel-btn i");
        const img = document.querySelector("#upload_image");
        let regExp = /[0-9a-zA-Z\^\&\'\@\{\}\[\]\,\$\=\!\-\#\(\)\.\%\+\~\_ ]+$/;
        function defaultBtnActive(){
            defaultBtn.click();
        }
        defaultBtn.addEventListener("change", function(){
            const file = this.files[0];
            if(file){
                const reader = new FileReader();
                reader.onload = function(){
                    const result = reader.result;
                    console.log(result)
                    img.src = result;
                    wrapper.classList.add("active");
                }
                cancelBtn.addEventListener("click", function(){
                    img.src = "";
                    wrapper.classList.remove("active");
                })
                reader.readAsDataURL(file);
            }
            if(this.value){
                let valueStore = this.value.match(regExp);
                fileName.textContent = valueStore;
            }
        });
    </script>
@stop

resources/views/admin/pages/index.blade.php
@extends('admin.layouts.master')
@section('content')


<div class="col-lg-12 grid-margin stretch-card" >
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{__('admin.pages')}}</h4>
            @if(Session::has('error'))
            <div class="alert alert-danger" role="alert">
                {{Session::get('error')}}
            </div>
            @endif
            <span> {{__('admin.show')}}</span>
            <select name="perPage" id="perPage"  onchange="changepaginate()">

                <option value="5" @if($per_page==5) selected @endif>5</option>
                <option value="10" @if($per_page==10) selected @endif>10</option>
                <option value="25" @if($per_page==25) selected @endif>25</option>
                <option value="50" @if($per_page==50) selected @endif>50</option>
            </select>
            <span>{{__('admin.entries')}}</span>
            <br><br>
            <form class="form-inline" method="GET" id="filter_form">
                <div class="form-group mb-2">
                    <label for="filter" class="col-sm-2 col-form-label" >Filter</label>
                    <input type="text" class="form-control" id="filter" name="filter" placeholder="Product name..."  >
                </div>
{{--                <button type="submit" class="btn btn-default mb-2">Filter</button>--}}
            </form>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>@sortablelink( 'id',__('admin.id'))</th>
                        <th> @sortablelink('name_en',__('admin.name_en')) </th>
                        <th> @sortablelink('name_ar',__('admin.name_ar')) </th>
                        <th> @sortablelink('created_at',__('admin.created_time')) </th>
                        <th> @sortablelink('updated_at',__('admin.updated_time')) </th>
                        <th> {{__('admin.action')}} </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($pages as $page)

                        <tr>
                        <td class="py-1">
                          {{$page['id']}}
                        </td>
                        <td>{{$page['name_en']}} </td>
                        <td>
                            {{$page['name_ar']}}
                        </td>
                        <td> {{$page['created_at']}}  </td>
                        <td> {{$page['updated_at']}}  </td>
                            <td>
                                <a href="" onclick="event.preventDefault(); deleteObject( '{{ route('Pages.destroy',$page['id']) }}' ) " style="list-style-type: none"><li class="mdi mdi-delete" style="font-size: 20px;"></li></a>
                                <a href="{{ route('Pages.edit',$page['id']) }}" style="list-style-type: none"><li class="mdi mdi-table-edit" style="font-size: 20px;"></li></a>
                            </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>

                <br><br>
                <div class="d-flex justify-content-center">
                    {{ $pages->appends(compact('per_page'))->links() }}

                </div>
                <p>
                    {{__('admin.displaying')}} {{$pages->count()}} {{__('admin.of')}} {{ $pages->total() }} {{__('admin.pages')}}.
                </p>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        const input = document.getElementById("filter");

        input.addEventListener('input', submitform);



        function deleteObject(url) {


            Swal.fire({
                title: ' <div style="color: black;" >{!! trans('admin.are_you_sure') !!}</div>',
                icon:"question",
                showCancelButton: true,
                confirmButtonText: '{!! trans('admin.confirm') !!}',
            }).then(function (result) {
                if (result.value != null) {
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {_method: 'DELETE', _token: '{{ csrf_token() }}'},
                        success: function (message) {
                            // location.reload();
                            if (message['error'])
                            {swal.fire(' <div style="color: black;" >{!! trans('admin.fail') !!}</div>',
                                    message['error'],
                                    "error");}
                            else
                            {
                                swal.fire(' <div style="color: black;" >{!! trans('admin.success') !!}</div>',
                                    message['success'],
                                    "success").then(function (result) {
                                    if (result.value != null) {
                                        location.reload();

                                    }
                                });
                            }
                        },
                        fail: function (e) {
                            swal("{!! trans('admin.fail') !!}", e.responseJSON.message, "error")
                        }
                    });
                }
            })
        }
        function changepaginate() {
            var paginate = document.getElementById("perPage").value;
            window.location = "{!! $pages->url(1) !!}&per_page=" + paginate;

        }
        function submitform() {
            console.log('ola')

            value = $('#filter').val();
            per_page = $('#perPage').val();
            $.ajax({
                type: 'get',
                url: '{{route('search')}}',
                data: {
                    'filter': value,
                    'per_page': per_page
                },
                success: function (data) {
                    $('tbody').html(data);
                }
            });
        }
{{--            document.getElementById("filter").focus();--}}


    </script>
@stop

resources/views/admin/pages/index_datatable.blade.php
@extends('admin.layouts.master')
@section('content')


    <div class="col-lg-12 grid-margin stretch-card" >
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{__('admin.pages')}}</h4>
                @if(Session::has('error'))
                    <div class="alert alert-danger" role="alert">
                        {{Session::get('error')}}
                    </div>
                @endif

                <div class="table-responsive">
                    <table id="products-table" class="table table-bordered table-hover" class="display" style="width:100%">
                        <thead>
                            <th>@sortablelink( 'id',__('admin.id'))</th>
                            <th> @sortablelink('name_en',__('admin.name_en')) </th>
                            <th> @sortablelink('name_ar',__('admin.name_ar')) </th>
                            <th> @sortablelink('created_at',__('admin.created_time')) </th>
                            <th> @sortablelink('updated_at',__('admin.updated_time')) </th>
                            <th> {{__('admin.action')}} </th>

                        </thead>
                        <tbody>

                        </tbody>
                    </table>

                    <br><br>
                    <div class="d-flex justify-content-center">
{{--                        {{ $pages->appends(compact('per_page'))->links() }}--}}

                    </div>
                    <p>
{{--                        {{__('admin.displaying')}} {{$pages->count()}} {{__('admin.of')}} {{ $pages->total() }} {{__('admin.pages')}}.--}}
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $('#products-table').DataTable({
                "serverSide": true,
                "ajax": {
                    url: "{{ action('App\Http\Controllers\admin\PageController@productsDataSource') }}",
                    method: "get"
                },
                "columnDefs" : [{
                    'targets': [4],
                    'orderable': false
                }],
            });
        });
        const input = document.getElementById("filter");

        input.addEventListener('input', submitform);



        function deleteObject(url) {


            Swal.fire({
                title: ' <div style="color: black;" >{!! trans('admin.are_you_sure') !!}</div>',
                icon:"question",
                showCancelButton: true,
                confirmButtonText: '{!! trans('admin.confirm') !!}',
            }).then(function (result) {
                if (result.value != null) {
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {_method: 'DELETE', _token: '{{ csrf_token() }}'},
                        success: function (message) {
                            // location.reload();
                            if (message['error'])
                            {swal.fire(' <div style="color: black;" >{!! trans('admin.fail') !!}</div>',
                                message['error'],
                                "error");}
                            else
                            {
                                swal.fire(' <div style="color: black;" >{!! trans('admin.success') !!}</div>',
                                    message['success'],
                                    "success").then(function (result) {
                                    if (result.value != null) {
                                        location.reload();

                                    }
                                });
                            }
                        },
                        fail: function (e) {
                            swal("{!! trans('admin.fail') !!}", e.responseJSON.message, "error")
                        }
                    });
                }
            })
        }
        {{--function changepaginate() {--}}
        {{--    var paginate = document.getElementById("perPage").value;--}}
        {{--    window.location = "{!! $pages->url(1) !!}&per_page=" + paginate;--}}

        {{--}--}}
        function submitform() {
            console.log('ola')

            value = $('#filter').val();
            per_page = $('#perPage').val();
            $.ajax({
                type: 'get',
                url: '{{route('search')}}',
                data: {
                    'filter': value,
                    'per_page': per_page
                },
                success: function (data) {
                    $('tbody').html(data);
                }
            });
        }
        {{--            document.getElementById("filter").focus();--}}


    </script>
@stop